import { useMemo } from 'react';
import { Link } from 'react-router-dom';
import ApperIcon from '@/components/ApperIcon';
import { useLocalQuery } from '@/hooks/useLocalTable';

export const route = { path: '/dashboard', layout: 'owner', access: 'public' };
export const nav = { icon: 'Gauge', label: 'Cockpit', section: 'Operations', order: 1 };

export default function Dashboard() {
  const { data: orders, loading, error, run } = useLocalQuery('SELECT * FROM orders ORDER BY created_at DESC', [], []);
  const { data: goals } = useLocalQuery('SELECT * FROM goals WHERE active = 1 ORDER BY created_at DESC', [], []);
  const active = (orders ?? []).filter(order => !['Delivered', 'Cancelled'].includes(order.status));
  const delivered = (orders ?? []).filter(order => order.status === 'Delivered');
  const earnings = delivered.reduce((sum, order) => sum + Number(order.earning || 0), 0);
  const goalProgress = useMemo(() => {
    const activeGoals = goals ?? [];
    if (!activeGoals.length) return 0;
    return Math.round(activeGoals.reduce((sum, goal) => sum + Math.min(1, Number(goal.saved) / Math.max(1, Number(goal.target))), 0) / activeGoals.length * 100);
  }, [goals]);

  return <div className="space-y-7">
    <section className="relative overflow-hidden rounded-[2rem] bg-primary p-6 text-primary-foreground md:p-9"><div className="absolute -right-12 -top-24 h-72 w-72 rounded-full border-[45px] border-primary-foreground/10" /><div className="relative z-10 flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><div className="mb-3 inline-flex items-center gap-2 rounded-full bg-primary-foreground/15 px-3 py-1 text-xs font-bold uppercase tracking-widest"><span className="h-2 w-2 rounded-full bg-success" /> Local-first cockpit</div><h1 className="font-heading text-5xl font-bold leading-none md:text-7xl">Run the shift.<br />Keep the data.</h1><p className="mt-4 max-w-xl text-primary-foreground/80">Orders, trips, GPS milestones and payments stay in your local SQLite database. Cloud backup is optional.</p></div><Link to="/live-run" className="inline-flex items-center justify-center gap-2 rounded-xl bg-accent px-5 py-3 font-bold text-accent-foreground transition hover:brightness-105 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary-foreground">Open live run <ApperIcon name="ArrowUpRight" /></Link></div></section>
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Tracked earnings" value={`₹${earnings.toLocaleString('en-IN')}`} detail={`${delivered.length} delivered`} icon="IndianRupee" /><Metric label="Orders in motion" value={active.length} detail="Open deliveries" icon="Package" /><Metric label="Total orders" value={(orders ?? []).length} detail="Stored on this device" icon="Database" /><Metric label="Goal progress" value={`${goalProgress}%`} detail={`${(goals ?? []).length} active goals`} icon="Target" /></section>
    <section className="grid gap-6 xl:grid-cols-[1.25fr_.75fr]">
      <div className="rounded-3xl border border-border bg-card p-5 md:p-6"><div className="mb-5 flex items-center justify-between"><div><h2 className="font-heading text-3xl font-bold">Active deliveries</h2><p className="text-sm text-muted-foreground">Current local queue</p></div><Link to="/orders" className="text-sm font-bold text-primary hover:underline">Manage orders →</Link></div>{loading ? <Loading /> : error ? <ErrorState message={error.message} retry={run} /> : active.length === 0 ? <Empty icon="PackageOpen" text="No active deliveries. Add an order when you accept your next job." href="/orders" action="Add order" /> : <div className="space-y-3">{active.slice(0, 6).map(order => <div key={order.id} className="flex flex-wrap items-center justify-between gap-3 rounded-2xl bg-muted/60 p-4"><div className="flex min-w-0 items-center gap-3"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-secondary text-secondary-foreground"><ApperIcon name="Package" /></span><div className="min-w-0"><strong className="block truncate">{order.code}</strong><span className="text-xs text-muted-foreground">{order.status} · {order.drop_address || 'No destination'}</span></div></div><strong className="tabular-nums">₹{Number(order.earning || 0).toFixed(0)}</strong></div>)}</div>}</div>
      <div className="rounded-3xl border border-border bg-card p-5 md:p-6"><div className="mb-5 flex items-center justify-between"><div><h2 className="font-heading text-3xl font-bold">Money goals</h2><p className="text-sm text-muted-foreground">Tracked locally</p></div><Link to="/goals" className="text-sm font-bold text-primary hover:underline">Manage →</Link></div>{(goals ?? []).length === 0 ? <Empty icon="Target" text="Create a savings target and track progress from completed work." href="/goals" action="Create goal" /> : <div className="space-y-5">{(goals ?? []).map(goal => { const percent = Math.min(100, Math.round(Number(goal.saved) / Math.max(1, Number(goal.target)) * 100)); return <div key={goal.id}><div className="mb-2 flex justify-between gap-3"><strong>{goal.name}</strong><span className="text-sm font-bold tabular-nums">{percent}%</span></div><div className="h-2.5 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-primary transition-all" style={{ width: `${percent}%` }} /></div><div className="mt-2 flex justify-between text-xs text-muted-foreground"><span>₹{Number(goal.saved).toLocaleString('en-IN')}</span><span>₹{Number(goal.target).toLocaleString('en-IN')}</span></div></div>; })}</div>}</div>
    </section>
    <section className="grid gap-4 md:grid-cols-3"><QuickLink href="/places" icon="MapPinned" title="Network" text="Manage platforms, restaurants, hubs and dark stores." /><QuickLink href="/insights" icon="ChartNoAxesCombined" title="Insights" text="See earnings, delivery rates and GPS activity." /><QuickLink href="/settings" icon="HardDrive" title="Backup & QR" text="Export your SQLite database and manage payment settings." /></section>
  </div>;
}

function Metric({ label, value, detail, icon }) { return <div className="rounded-3xl border border-border bg-card p-5"><div className="mb-4 flex items-center justify-between"><span className="text-sm font-semibold text-muted-foreground">{label}</span><ApperIcon name={icon} className="text-primary" /></div><div className="font-heading text-4xl font-bold tabular-nums">{value}</div><p className="mt-1 text-xs text-muted-foreground">{detail}</p></div>; }
function Loading() { return <div className="space-y-3">{[1, 2, 3].map(item => <div key={item} className="h-20 animate-pulse rounded-2xl bg-muted" />)}</div>; }
function ErrorState({ message, retry }) { return <div className="rounded-xl bg-destructive/10 p-4 text-sm text-destructive">{message}<button onClick={retry} className="ml-3 underline">Retry</button></div>; }
function Empty({ icon, text, href, action }) { return <div className="grid justify-items-center rounded-2xl border border-dashed border-border p-7 text-center"><ApperIcon name={icon} className="mb-3 text-muted-foreground" /><p className="mb-4 max-w-xs text-sm text-muted-foreground">{text}</p><Link to={href} className="rounded-lg bg-primary px-4 py-2 text-sm font-bold text-primary-foreground">{action}</Link></div>; }
function QuickLink({ href, icon, title, text }) { return <Link to={href} className="group rounded-3xl border border-border bg-card p-5 transition hover:-translate-y-0.5 hover:shadow-(--shadow-sm) focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"><div className="mb-3 flex items-center justify-between"><ApperIcon name={icon} className="text-primary" /><ApperIcon name="ArrowUpRight" className="text-muted-foreground transition group-hover:text-primary" /></div><h3 className="font-heading text-2xl font-bold">{title}</h3><p className="mt-1 text-sm text-muted-foreground">{text}</p></Link>; }
