import { useState } from 'react';
import { useFetch } from '@/hooks/useFetch';
import { sdk } from '@/services/sdk';
import ApperIcon from '@/components/ApperIcon';

export const route={path:'/goals',layout:'owner',access:'authenticated'};
export const nav={icon:'Wallet',label:'Goals & money',section:'Shift',order:5};
const FIELDS=['Name','target_c','saved_c','deadline_c','rule_c','ruleValue_c','active_c'];
export default function Goals(){const [open,setOpen]=useState(false);const [editing,setEditing]=useState(null);const [form,setForm]=useState({Name:'',target_c:'',saved_c:'0',deadline_c:'',rule_c:'Percent of earnings',ruleValue_c:'10',active_c:true});const [saving,setSaving]=useState(false);const [message,setMessage]=useState('');const {data,loading,error,run}=useFetch(async()=>{const r=await sdk.table('goals_c').select(FIELDS).orderByDesc('CreatedOn').page(1,100).fetch();if(!r.success)throw new Error(r.message);return r.data??[];},[]);const goals=data??[];const total=goals.reduce((s,g)=>s+Number(g.saved_c||0),0);const targets=goals.reduce((s,g)=>s+Number(g.target_c||0),0);
function edit(g){setEditing(g);setForm({Name:g.Name,target_c:g.target_c,saved_c:g.saved_c,deadline_c:g.deadline_c||'',rule_c:g.rule_c,ruleValue_c:g.ruleValue_c,active_c:g.active_c});setOpen(true);}function create(){setEditing(null);setForm({Name:'',target_c:'',saved_c:'0',deadline_c:'',rule_c:'Percent of earnings',ruleValue_c:'10',active_c:true});setOpen(true);}
async function submit(e){e.preventDefault();setSaving(true);setMessage('');try{const payload={Name:form.Name,target_c:Number(form.target_c),saved_c:Number(form.saved_c||0),deadline_c:form.deadline_c||null,rule_c:form.rule_c,ruleValue_c:Number(form.ruleValue_c||0),active_c:!!form.active_c};const r=editing?await sdk.table('goals_c').update({Id:editing.Id,...payload}):await sdk.table('goals_c').create(payload);if(!r.success)throw new Error(r.messages?.[0]||r.message||'Save failed');setOpen(false);setMessage(editing?'Goal updated.':'Goal created.');await run();}catch(e){setMessage(e.message);}finally{setSaving(false);}}
async function remove(g){if(!window.confirm(`Delete goal “${g.Name}”?`))return;const r=await sdk.table('goals_c').remove(g.Id);if(!r.success)setMessage(r.messages?.[0]||r.message||'Delete failed');else{setMessage('Goal deleted.');await run();}}
return <div className="space-y-6"><header className="flex flex-wrap items-end justify-between gap-4"><div><p className="mb-2 text-xs font-bold uppercase tracking-[.18em] text-primary">Give every rupee a job</p><h1 className="font-heading text-5xl font-bold">Goals & money</h1><p className="mt-2 text-muted-foreground">Set targets and choose a rule for allocating your tracked earnings.</p></div><button onClick={create} className="inline-flex items-center gap-2 rounded-xl bg-primary px-4 py-3 font-bold text-primary-foreground hover:opacity-90 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"><ApperIcon name="Plus"/> New goal</button></header>
<div className="grid gap-4 md:grid-cols-3"><div className="rounded-3xl bg-primary p-6 text-primary-foreground"><p className="text-sm text-primary-foreground/75">Allocated so far</p><div className="mt-2 font-heading text-4xl font-bold">₹{total.toLocaleString('en-IN')}</div></div><div className="rounded-3xl border border-border bg-card p-6"><p className="text-sm text-muted-foreground">Combined goal targets</p><div className="mt-2 font-heading text-4xl font-bold">₹{targets.toLocaleString('en-IN')}</div></div><div className="rounded-3xl border border-border bg-card p-6"><p className="text-sm text-muted-foreground">Overall funded</p><div className="mt-2 font-heading text-4xl font-bold">{targets?Math.min(100,Math.round(total/targets*100)):0}%</div></div></div>
{message&&<div role="status" className="rounded-xl bg-muted p-3 text-sm">{message}</div>}
{open&&<form onSubmit={submit} className="grid gap-3 rounded-3xl border border-border bg-card p-5 md:grid-cols-2"><h2 className="md:col-span-2 font-heading text-2xl font-bold">{editing?'Edit':'Create'} a money goal</h2><input required placeholder="Goal name" value={form.Name} onChange={e=>setForm({...form,Name:e.target.value})} className="rounded-xl border border-input bg-background px-3 py-3"/><input required type="number" min="1" placeholder="Target ₹" value={form.target_c} onChange={e=>setForm({...form,target_c:e.target.value})} className="rounded-xl border border-input bg-background px-3 py-3"/><input type="number" min="0" placeholder="Already allocated ₹" value={form.saved_c} onChange={e=>setForm({...form,saved_c:e.target.value})} className="rounded-xl border border-input bg-background px-3 py-3"/><input type="date" value={form.deadline_c} onChange={e=>setForm({...form,deadline_c:e.target.value})} className="rounded-xl border border-input bg-background px-3 py-3"/><select value={form.rule_c} onChange={e=>setForm({...form,rule_c:e.target.value})} className="rounded-xl border border-input bg-background px-3 py-3">{['Fixed per delivery','Percent of earnings','Daily remainder'].map(x=><option key={x}>{x}</option>)}</select><input type="number" min="0" step=".01" placeholder="Rule value (₹ or %)" value={form.ruleValue_c} onChange={e=>setForm({...form,ruleValue_c:e.target.value})} className="rounded-xl border border-input bg-background px-3 py-3"/><label className="flex items-center gap-2"><input type="checkbox" checked={!!form.active_c} onChange={e=>setForm({...form,active_c:e.target.checked})}/> Goal active</label><p className="md:col-span-2 rounded-xl bg-warning-muted p-3 text-sm text-warning-foreground">Allocation rules are saved as your plan. Automatic posting from earnings needs a verified earnings feed or a confirmed manual earnings entry; this preview does not move real money.</p><div className="flex gap-2 md:col-span-2"><button disabled={saving} className="rounded-xl bg-primary px-5 py-3 font-bold text-primary-foreground disabled:opacity-50">{saving?'Saving…':'Save goal'}</button><button type="button" onClick={()=>setOpen(false)} className="rounded-xl bg-muted px-5 py-3 font-bold">Cancel</button></div></form>}
{loading?<div className="grid gap-4 md:grid-cols-2">{[1,2].map(i=><div key={i} className="h-48 animate-pulse rounded-3xl bg-muted"/>)}</div>:error?<div className="rounded-xl bg-destructive/10 p-4 text-destructive">{error.message}<button onClick={run} className="ml-3 underline">Retry</button></div>:goals.length===0?<div className="rounded-3xl border border-dashed border-border p-10 text-center"><ApperIcon name="Target" className="mx-auto mb-3 text-muted-foreground"/><p className="mb-4 text-muted-foreground">Create a goal to start giving your earnings a purpose.</p><button onClick={create} className="rounded-xl bg-primary px-4 py-2 font-bold text-primary-foreground">Create your first goal</button></div>:<div className="grid gap-4 xl:grid-cols-2">{goals.map(g=>{const pct=Math.min(100,Math.round(Number(g.saved_c||0)/Math.max(1,Number(g.target_c||1))*100));return <article key={g.Id} className="rounded-3xl border border-border bg-card p-6"><div className="mb-5 flex items-start justify-between"><div><span className="mb-2 inline-flex rounded-full bg-secondary px-2.5 py-1 text-xs font-bold text-secondary-foreground">{g.active_c?'Active':'Paused'}</span><h2 className="font-heading text-3xl font-bold">{g.Name}</h2><p className="text-sm text-muted-foreground">{g.rule_c} · {g.ruleValue_c}{g.rule_c==='Percent of earnings'?'%':' ₹'}</p></div><div className="flex gap-1"><button aria-label={`Edit ${g.Name}`} onClick={()=>edit(g)} className="rounded-lg p-2 hover:bg-muted focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"><ApperIcon name="Pencil"/></button><button aria-label={`Delete ${g.Name}`} onClick={()=>remove(g)} className="rounded-lg p-2 text-destructive hover:bg-muted focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"><ApperIcon name="Trash2"/></button></div></div><div className="mb-3 flex items-end justify-between"><strong className="font-heading text-4xl">₹{Number(g.saved_c||0).toLocaleString('en-IN')}</strong><span className="text-sm text-muted-foreground">of ₹{Number(g.target_c||0).toLocaleString('en-IN')}</span></div><div className="h-3 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-primary" style={{width:`${pct}%`}}/></div><div className="mt-3 flex justify-between text-xs text-muted-foreground"><span>{pct}% funded</span><span>{g.deadline_c?`Target date ${g.deadline_c}`:'No deadline'}</span></div></article>;})}</div>}</div>;
}
