import { useFetch } from '@/hooks/useFetch';
import { sdk } from '@/services/sdk';
import ApperIcon from '@/components/ApperIcon';

export const route={path:'/insights',layout:'owner',access:'authenticated'};
export const nav={icon:'ChartNoAxesCombined',label:'Insights',section:'Shift',order:6};
const OF=['Name','platform_c','phase_c','earning_c','distanceKm_c','minutes_c','CreatedOn'];
const EF=['Name','eventType_c','latitude_c','longitude_c','accuracyM_c','capturedAt_c','source_c'];
export default function Insights(){const {data:orders,loading,error,run}=useFetch(async()=>{const r=await sdk.table('orders_c').select(OF).orderByDesc('CreatedOn').page(1,500).fetch();if(!r.success)throw new Error(r.message);return r.data??[];},[]);const {data:events}=useFetch(async()=>{const r=await sdk.table('journey_events_c').select(EF).orderByDesc('CreatedOn').page(1,500).fetch();if(!r.success)throw new Error(r.message);return r.data??[];},[]);const rows=orders??[];const delivered=rows.filter(o=>o.phase_c==='Delivered');const earnings=delivered.reduce((s,o)=>s+Number(o.earning_c||0),0);const distance=delivered.reduce((s,o)=>s+Number(o.distanceKm_c||0),0);const minutes=delivered.reduce((s,o)=>s+Number(o.minutes_c||0),0);const perKm=distance?earnings/distance:0;const perHour=minutes?earnings/(minutes/60):0;const platforms={};delivered.forEach(o=>{const key=o.platform_c?.Name||'Unassigned';platforms[key]=(platforms[key]||0)+Number(o.earning_c||0);});const max=Math.max(1,...Object.values(platforms));const locations=(events??[]).filter(e=>e.latitude_c!=null&&e.longitude_c!=null);const hourCounts={};delivered.forEach(o=>{const h=new Date(o.CreatedOn).getHours();const label=`${String(h).padStart(2,'0')}:00`;hourCounts[label]=(hourCounts[label]||0)+1;});const peak=Object.entries(hourCounts).sort((a,b)=>b[1]-a[1])[0];
return <div className="space-y-6"><header><p className="mb-2 text-xs font-bold uppercase tracking-[.18em] text-primary">Turn activity into advantage</p><h1 className="font-heading text-5xl font-bold">Shift intelligence</h1><p className="mt-2 text-muted-foreground">Insights are calculated from your recorded orders and location events.</p></header>
{loading?<div className="grid gap-4 md:grid-cols-3">{[1,2,3].map(i=><div key={i} className="h-36 animate-pulse rounded-3xl bg-muted"/>)}</div>:error?<div className="rounded-xl bg-destructive/10 p-4 text-destructive">{error.message}<button onClick={run} className="ml-3 underline">Retry</button></div>:<><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Stat label="Tracked delivery earnings" value={`₹${earnings.toFixed(0)}`} icon="IndianRupee"/><Stat label="Earnings per active hour*" value={`₹${perHour.toFixed(0)}`} icon="Clock"/><Stat label="Earnings per delivery km" value={`₹${perKm.toFixed(1)}`} icon="Route"/><Stat label="GPS milestone points" value={locations.length} icon="MapPin"/></section>
<section className="grid gap-6 xl:grid-cols-[1fr_1fr]"><div className="rounded-3xl border border-border bg-card p-6"><h2 className="font-heading text-3xl font-bold">Earnings by platform</h2><p className="mb-6 text-sm text-muted-foreground">Tracked completed orders only</p>{Object.keys(platforms).length===0?<p className="text-sm text-muted-foreground">Complete and log orders to build a platform comparison.</p>:<div className="space-y-5">{Object.entries(platforms).sort((a,b)=>b[1]-a[1]).map(([name,value])=><div key={name}><div className="mb-2 flex justify-between"><strong>{name}</strong><span className="font-bold">₹{value.toFixed(0)}</span></div><div className="h-3 rounded-full bg-muted"><div className="h-3 rounded-full bg-primary" style={{width:`${value/max*100}%`}}/></div></div>)}</div>}</div>
<div className="rounded-3xl border border-border bg-card p-6"><h2 className="font-heading text-3xl font-bold">Your shift signals</h2><p className="mb-5 text-sm text-muted-foreground">Simple observations from the data currently available</p><div className="space-y-3">{peak?<Insight icon="Clock" title={`Most recorded completions: ${peak[0]}`} body={`${peak[1]} tracked deliveries fall in this hour. Collect more days of data before treating it as a reliable pattern.`}/>:<Insight icon="Clock" title="Build your hourly pattern" body="Record delivery completion times to see which hours have been productive."/>}<Insight icon="Gauge" title={`${perKm.toFixed(1)} rupees per km`} body="This uses entered delivery distance and earnings; it does not subtract fuel, maintenance or unpaid repositioning yet."/><Insight icon="MapPinned" title={`${locations.length} location milestones`} body="Pickup and delivery clusters become more meaningful as you record accurate GPS points across multiple shifts."/></div></div></section>
<section className="rounded-3xl border border-border bg-card p-6"><div className="mb-4 flex items-center justify-between"><div><h2 className="font-heading text-3xl font-bold">Location heatmap data</h2><p className="text-sm text-muted-foreground">Recorded GPS events, summarized by coordinates</p></div><span className="rounded-full bg-secondary px-3 py-1 text-xs font-bold text-secondary-foreground">{locations.length} points</span></div>{locations.length===0?<p className="text-sm text-muted-foreground">No GPS points yet. Record pickup/drop milestones during your runs to start building your personal heatmap.</p>:<><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{locations.map((e,i)=><div key={e.Id} className="rounded-2xl bg-muted/60 p-4"><div className="mb-2 flex items-center gap-2"><ApperIcon name="MapPin" className="text-primary"/><strong>{e.eventType_c}</strong></div><p className="font-mono text-sm">{Number(e.latitude_c).toFixed(5)}, {Number(e.longitude_c).toFixed(5)}</p><p className="mt-1 text-xs text-muted-foreground">±{e.accuracyM_c??'—'} m · {e.source_c||'unknown source'}</p></div>)}</div><p className="mt-4 text-xs text-muted-foreground">This preview lists captured coordinates; a native map/heat layer needs a map SDK and Android location capture.</p></>}</section><p className="text-xs text-muted-foreground">*Hourly rate uses entered delivery durations only, not total online time. Small demo samples are not predictive.</p></>}
</div>;
}
function Stat({label,value,icon}){return <div className="rounded-3xl border border-border bg-card p-5"><div className="mb-4 flex justify-between text-muted-foreground"><span className="text-sm font-semibold">{label}</span><ApperIcon name={icon} className="text-primary"/></div><strong className="font-heading text-4xl">{value}</strong></div>;}
function Insight({icon,title,body}){return <div className="flex gap-3 rounded-2xl bg-muted/60 p-4"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-secondary text-secondary-foreground"><ApperIcon name={icon}/></span><div><strong>{title}</strong><p className="mt-1 text-sm leading-relaxed text-muted-foreground">{body}</p></div></div>;}
