import { useState } from 'react';
import { useFetch } from '@/hooks/useFetch';
import { sdk } from '@/services/sdk';
import ApperIcon from '@/components/ApperIcon';

export const route = { path: '/orders', layout: 'owner', access: 'authenticated' };
export const nav = { icon: 'PackageCheck', label: 'Order history', section: 'Shift', order: 3 };
const FIELDS = ['Name','platform_c','orderCode_c','phase_c','pickup_c','dropAddress_c','earning_c','distanceKm_c','minutes_c','CreatedOn'];
export default function Orders() {
  const [search, setSearch] = useState(''); const [phase, setPhase] = useState('All'); const [sort, setSort] = useState('new'); const [showForm, setShowForm] = useState(false); const [form, setForm] = useState({ orderCode_c:'', platformName:'Swiggy', phase_c:'Accepted', earning_c:'', dropAddress_c:'' }); const [saving, setSaving] = useState(false); const [message, setMessage] = useState('');
  const { data, loading, error, run } = useFetch(async () => { const r=await sdk.table('orders_c').select(FIELDS).orderByDesc('CreatedOn').page(1,200).fetch(); if(!r.success) throw new Error(r.message); return r.data??[]; }, []);
  const rows=(data??[]).filter(o => `${o.Name} ${o.orderCode_c} ${o.platform_c?.Name}`.toLowerCase().includes(search.toLowerCase()) && (phase==='All'||o.phase_c===phase)).sort((a,b)=>sort==='earning'?Number(b.earning_c||0)-Number(a.earning_c||0):sort==='old'?String(a.CreatedOn).localeCompare(String(b.CreatedOn)):String(b.CreatedOn).localeCompare(String(a.CreatedOn)));
  async function create(e){e.preventDefault();setSaving(true);setMessage('');try{const platforms=await sdk.table('platforms_c').select(['Name']).where(window.ApperSDK.CoreSDK.eq('Name',form.platformName)).page(1,1).fetch();if(!platforms.success||!platforms.data?.[0])throw new Error('Add this platform first in Places & Platforms.');const r=await sdk.table('orders_c').create({Name:`${form.orderCode_c} · ${form.platformName}`,orderCode_c:form.orderCode_c,platform_c:platforms.data[0].Id,phase_c:form.phase_c,earning_c:Number(form.earning_c||0),dropAddress_c:form.dropAddress_c});if(!r.success)throw new Error(r.messages?.[0]||r.message||'Could not create order.');setShowForm(false);setForm({orderCode_c:'',platformName:'Swiggy',phase_c:'Accepted',earning_c:'',dropAddress_c:''});setMessage('Order added.');await run();}catch(err){setMessage(err.message);}finally{setSaving(false);}}
  async function remove(record){if(!window.confirm(`Delete ${record.orderCode_c || record.Name}?`))return;setMessage('Deleting…');const r=await sdk.table('orders_c').remove(record.Id);if(!r.success)setMessage(r.messages?.[0]||r.message||'Delete failed');else{setMessage('Order deleted.');await run();}}
  return <div className="space-y-6"><header className="flex flex-wrap items-end justify-between gap-4"><div><p className="mb-2 text-xs font-bold uppercase tracking-[.18em] text-primary">All platforms, one ledger</p><h1 className="font-heading text-5xl font-bold">Order history</h1><p className="mt-2 text-muted-foreground">Search, filter and review each tracked delivery.</p></div><button onClick={()=>setShowForm(!showForm)} className="inline-flex items-center gap-2 rounded-xl bg-primary px-4 py-3 font-bold text-primary-foreground hover:opacity-90 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"><ApperIcon name="Plus"/> Add order</button></header>
  {showForm&&<form onSubmit={create} className="grid gap-3 rounded-3xl border border-border bg-card p-5 md:grid-cols-2"><h2 className="md:col-span-2 font-heading text-2xl font-bold">Log accepted order</h2><input required placeholder="Order ID / code" value={form.orderCode_c} onChange={e=>setForm({...form,orderCode_c:e.target.value})} className="rounded-xl border border-input bg-background px-3 py-3"/><select value={form.platformName} onChange={e=>setForm({...form,platformName:e.target.value})} className="rounded-xl border border-input bg-background px-3 py-3"><option>Swiggy</option><option>Shadowfax</option><option>MagicFleet</option></select><input type="number" min="0" step=".01" placeholder="Expected earning ₹" value={form.earning_c} onChange={e=>setForm({...form,earning_c:e.target.value})} className="rounded-xl border border-input bg-background px-3 py-3"/><input placeholder="Drop address" value={form.dropAddress_c} onChange={e=>setForm({...form,dropAddress_c:e.target.value})} className="rounded-xl border border-input bg-background px-3 py-3"/><div className="flex gap-2 md:col-span-2"><button disabled={saving} className="rounded-xl bg-primary px-5 py-3 font-bold text-primary-foreground disabled:opacity-50">{saving?'Saving…':'Save order'}</button><button type="button" onClick={()=>setShowForm(false)} className="rounded-xl bg-muted px-5 py-3 font-bold text-foreground">Cancel</button></div></form>}
  {message&&<div role="status" className="rounded-xl bg-muted p-3 text-sm">{message}</div>}
  <div className="flex flex-wrap gap-3 rounded-2xl border border-border bg-card p-3"><div className="flex min-w-48 flex-1 items-center gap-2 rounded-xl bg-muted px-3"><ApperIcon name="Search" className="text-muted-foreground"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search code or platform" className="w-full bg-transparent py-3 outline-none"/></div><select value={phase} onChange={e=>setPhase(e.target.value)} className="rounded-xl border border-input bg-background px-3 py-2"><option>All</option>{['Accepted','To Pickup','Arrived Pickup','Picked Up','To Drop','Delivered','Cancelled','Issue'].map(x=><option key={x}>{x}</option>)}</select><select value={sort} onChange={e=>setSort(e.target.value)} className="rounded-xl border border-input bg-background px-3 py-2"><option value="new">Newest first</option><option value="old">Oldest first</option><option value="earning">Highest earning</option></select></div>
  {loading?<div className="space-y-3">{[1,2,3].map(i=><div key={i} className="h-20 animate-pulse rounded-2xl bg-muted"/>)}</div>:error?<div className="rounded-xl bg-destructive/10 p-4 text-destructive">{error.message}<button onClick={run} className="ml-3 underline">Retry</button></div>:rows.length===0?<div className="rounded-3xl border border-dashed border-border p-10 text-center"><ApperIcon name="PackageOpen" className="mx-auto mb-3 text-muted-foreground"/><p className="text-muted-foreground">No orders match. Clear filters or add your first tracked order.</p></div>:<div className="overflow-hidden rounded-3xl border border-border bg-card"><div className="hidden grid-cols-[1.5fr_1fr_1fr_.7fr_auto] gap-3 bg-muted px-5 py-3 text-xs font-bold uppercase tracking-wider text-muted-foreground md:grid"><span>Order</span><span>Platform</span><span>Phase</span><span>Earning</span><span>Actions</span></div>{rows.map(o=><div key={o.Id} className="grid gap-2 border-t border-border px-5 py-4 first:border-0 md:grid-cols-[1.5fr_1fr_1fr_.7fr_auto] md:items-center md:gap-3"><div><strong className="block">{o.orderCode_c||o.Name}</strong><small className="text-muted-foreground">{o.pickup_c?.Name||'Pickup not linked'}</small></div><div className="text-sm">{o.platform_c?.Name||'—'}</div><div><span className="inline-flex rounded-full bg-secondary px-2.5 py-1 text-xs font-bold text-secondary-foreground">{o.phase_c}</span></div><strong>₹{Number(o.earning_c||0).toFixed(0)}</strong><button aria-label={`Delete ${o.orderCode_c||o.Name}`} onClick={()=>remove(o)} className="justify-self-start rounded-lg p-2 text-destructive hover:bg-muted focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"><ApperIcon name="Trash2"/></button></div>)}</div>}</div>;
}
